### ISSUE TITLE
Add a CONTRIBUTING.md + brief to-do list + comparison + status 

### ISSUE THREAD

**Issue by LappleApple** [zalando/baigan-config#10]
Hey guys -- I had a delivery head look at this, and he feels like there could be other, similar projects that do this. Can you include in your README 1-2 sentences about how this project differs from similar tools, and name those tools? This will be helpful to potential users out there.

Also, how would people contribute? Listing a few opportunities and adding a contributing file with guidelines makes this more community-friendly.

Finally, what's the status? Is it being used in production at Zalando or elsewhere?

**Comment by amjedonline** [comment]
Hi, 
this is being used in the cart-service component of Checkout/Fashion store team.
There are a whole lot of things that can be contributed to the project, for which I will soon update the Readme.

**Comment by LappleApple** [comment]
OK, great. Just remember, these contributions should be for *anyone* to make -- not just non-Zalandos. I'll edit the README after you add those contrib ideas. :)

**Comment by amjedonline** [comment]
I have written them already, please check the CONTRIBUTING.md and let me know.

**Comment by LappleApple** [comment]
Cool. I'm going to pull some of that and place it on the README, but good work!
